name: Politica
version: '${project.version}'
main: it.hero.politica.Politica
api-version: 1.16
softdepend: [HolographicDisplays,PlaceholderAPI,LuckPerms,ProtocolLib]
authors: [ 1100hero ]
description: Plugin creato su commissione per Bisignano, permette di gestire la politica del server.
commands:
  elezioni:
    description: "Permette di iniziare o terminare le elezioni."
  politica:
    description: "Permette di ricaricare il config della politica."
  creapartito:
    description: "Permette di creare un partito."
  givevoteblock:
    description: "Permette di givvare il blocco dove effettuare le votazioni."
  partito:
    description: "Permette di eseguire i comandi del partito."
  partychat:
    description: "Permette di scrivere nella chat del partito."
    aliases: [pc]
  politicahelp:
    description: "Permette di visualizzare la lista dei comandi del plugin."
    aliases: [ph]
  partylist:
    description: "Permette di visualizzare tutti i partiti registrati."
    aliases: [pl]
  politicahelpadmin:
    description: "Permette di visualizzare la lista dei comandi del plugin di un admin."
    aliases: [pha]
  detesserati:
    description: "Permette di detesserarti dal partito."